<a href="https://colab.research.google.com/github/Nabila2255/221230025-Pengantar-ML/blob/main/221230025_Pengantar_ML/week_02/latihan_praktikum_4_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

# Simulasi batch data: 32 samples, 10 features
batch_size, n_features = 32, 10
X = torch.randn(batch_size, n_features)
weights = torch.randn(n_features, 1)
bias = torch.randn(1)

# 1. Linear Layer: y = XW + b
def linear_layer(X, W, b):
    return X @ W + b   # atau torch.matmul(X, W) + b

output = linear_layer(X, weights, bias)

# 2. ReLU Activation
def relu_activation(tensor):
    return torch.maximum(torch.tensor(0.0), tensor)
    # bisa juga: return torch.clamp(tensor, min=0)

activated = relu_activation(output)

# 3. Batch Normalization sederhana
def simple_batch_norm(tensor, eps=1e-5):
    mean = tensor.mean(dim=0, keepdim=True)   # rata-rata per feature
    std = tensor.std(dim=0, keepdim=True)     # std per feature
    return (tensor - mean) / (std + eps)

normalized = simple_batch_norm(X)

# 4. One-hot encoding manual
def one_hot_pytorch(labels, num_classes):
    one_hot = torch.zeros(labels.size(0), num_classes)
    one_hot[torch.arange(labels.size(0)), labels] = 1
    return one_hot

labels = torch.randint(0, 3, (10,))
one_hot = one_hot_pytorch(labels, num_classes=3)

# Print output
print("✅ Linear layer output (first 5 rows):\n", output[:5])
print("\n✅ ReLU activated output (first 5 rows):\n", activated[:5])
print("\n✅ Batch normalized X (first 5 rows):\n", normalized[:5])
print("\n✅ One-hot encoded labels:\n", one_hot)

# Manual Matrix Multiplication
def manual_matrix_multiply(A, B):
    rows_A, cols_A = A.shape
    rows_B, cols_B = B.shape
    assert cols_A == rows_B, "Matrix dimensions must align"

    result = torch.zeros((rows_A, cols_B))
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                result[i, j] += A[i, k] * B[k, j]
    return result

# Test dengan matriks kecil
A = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
B = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

manual_result = manual_matrix_multiply(A, B)
torch_result = torch.matmul(A, B)

# Validasi
assert output.shape == (batch_size, 1), "Linear output shape incorrect"
assert torch.all(activated >= 0), "ReLU should be >= 0"
assert normalized.shape == X.shape, "Batch norm should preserve shape"
assert one_hot.shape == (10, 3), "One-hot shape incorrect"
assert torch.allclose(manual_result, torch_result), "Manual multiplication incorrect"

print("\n✅ Manual matrix multiplication result:\n", manual_result)
print("\n✅ Torch.matmul result:\n", torch_result)
print("✅ Semua implementasi PyTorch selesai")

✅ Linear layer output (first 5 rows):
 tensor([[-1.2589],
        [ 1.6499],
        [-4.2121],
        [ 3.1921],
        [-2.9388]])

✅ ReLU activated output (first 5 rows):
 tensor([[0.0000],
        [1.6499],
        [0.0000],
        [3.1921],
        [0.0000]])

✅ Batch normalized X (first 5 rows):
 tensor([[-2.4374e-01,  1.1389e+00,  4.4769e-01,  3.7722e-01,  4.8399e-01,
         -1.3010e+00,  2.1212e+00,  1.6785e-01, -4.1558e-01, -6.8701e-01],
        [-4.8633e-02, -1.0698e+00,  1.1737e+00, -3.0958e-01, -2.1106e-01,
         -7.1105e-01, -1.4975e-01, -8.4268e-01,  1.8843e+00, -3.1198e-01],
        [ 7.9979e-01,  1.9405e-01,  2.7179e-01, -8.1840e-01, -1.3244e+00,
          1.9395e-01,  2.3525e+00, -8.3428e-01, -6.7410e-01, -1.3769e+00],
        [-8.7210e-01, -8.7246e-01,  7.5813e-01, -5.6908e-02, -2.0323e-04,
         -1.9358e-02, -2.7097e-02, -2.5327e-01, -1.4304e+00,  1.3003e+00],
        [ 6.0683e-01, -6.5210e-01, -1.9557e+00, -1.7632e-01, -1.7756e+00,
         -1.0741e+00, -