<a href="https://colab.research.google.com/github/Nabila2255/221230025-Pengantar-ML/blob/main/week-02/latihan_praktikum_2_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# TODO 1: Normalisasi Z-score: (x - mean) / std
def z_score_normalization(data):
    """
    Melakukan normalisasi Z-score agar mean=0 dan std=1
    """
    if data.size == 0:
        raise ValueError("Input data tidak boleh kosong")
    mean = np.mean(data, axis=0)
    std = np.std(data, axis=0)
    return (data - mean) / std

# TODO 2: Handle outliers - clip values beyond 3 std
def handle_outliers(data, std_threshold=3):
    """
    Mengganti nilai yang lebih dari threshold*std menjadi batas terdekat
    """
    if data.size == 0:
        raise ValueError("Input data tidak boleh kosong")
    mean = np.mean(data, axis=0)
    std = np.std(data, axis=0)
    lower = mean - std_threshold * std
    upper = mean + std_threshold * std
    return np.clip(data, lower, upper)

# TODO 3: One-hot encoding untuk label kategorikal
def one_hot_encoding(labels):
    """
    Konversi label kategorikal ke bentuk one-hot encoding
    Input: [0, 1, 2] -> Output: [[1,0,0],[0,1,0],[0,0,1]]
    """
    if labels.size == 0:
        raise ValueError("Labels tidak boleh kosong")
    n_classes = np.max(labels) + 1
    return np.eye(n_classes)[labels]

# TODO 4: Train-test split manual
def train_test_split_numpy(X, y, test_size=0.2, seed=42):
    """
    Membagi dataset menjadi train & test tanpa sklearn
    """
    if len(X) != len(y):
        raise ValueError("Jumlah X dan y harus sama")
    np.random.seed(seed)
    indices = np.arange(len(X))
    np.random.shuffle(indices)
    test_size = int(len(X) * test_size)
    test_idx = indices[:test_size]
    train_idx = indices[test_size:]
    return X[train_idx], X[test_idx], y[train_idx], y[test_idx]

# ==== TEST IMPLEMENTASI ====
np.random.seed(42)
X = np.random.randn(100, 5) * 10 + 5  # Mean=5, Std=10

X_normalized = z_score_normalization(X)
X_cleaned = handle_outliers(X_normalized)
labels = np.array([0, 1, 2, 0, 1, 2, 0])
one_hot_labels = one_hot_encoding(labels)
X_train, X_test, y_train, y_test = train_test_split_numpy(X, np.random.randint(0, 3, 100))

# Assertion untuk validasi
assert X_normalized.shape == X.shape, "Shape should remain same"
assert np.allclose(X_normalized.mean(), 0, atol=1e-10), "Mean should be ~0 after z-score"
assert np.allclose(X_normalized.std(), 1, atol=1e-10), "Std should be ~1 after z-score"

print("✅ NumPy operations completed")
print("X_normalized:\n", X_normalized[:5])
print("X_cleaned:\n", X_cleaned[:5])
print("One-hot labels:\n", one_hot_labels)

✅ NumPy operations completed
X_normalized:
 [[ 0.604418   -0.21979528  0.75746006  1.461092   -0.18919425]
 [-0.21141045  1.53420502  0.87977344 -0.62585547  0.53845484]
 [-0.46735006 -0.55422449  0.34303561 -2.13809665 -1.58578836]
 [-0.57771567 -1.1129603   0.41687036 -1.08519209 -1.2929218 ]
 [ 1.68601234 -0.30916828  0.16486193 -1.62640854 -0.47982667]]
X_cleaned:
 [[ 0.604418   -0.21979528  0.75746006  1.461092   -0.18919425]
 [-0.21141045  1.53420502  0.87977344 -0.62585547  0.53845484]
 [-0.46735006 -0.55422449  0.34303561 -2.13809665 -1.58578836]
 [-0.57771567 -1.1129603   0.41687036 -1.08519209 -1.2929218 ]
 [ 1.68601234 -0.30916828  0.16486193 -1.62640854 -0.47982667]]
One-hot labels:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
